version: "3.9"
services:
  redis:
    image: "redis:alpine"
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping", "|", "grep", "PONG"]
      timeout: 5s
      retries: 5
      start_period: 5s
  memcached:
    image: "memcached:alpine"
  mysql:
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  nginx:
    image: "openresty/openresty:alpine"
    ports: 
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      redis:
        condition: service_healthy
      memcached:
        condition: service_started
      mysql:
        condition: service_started
